Add Justifications components and module
Asymmetrik/mean2-starter pull request #60
Opened 2017-01-17 19:21 UTC by allen12

Adding a new feature: a reusable modal with a typeahead designed for entering in justifications with a history cache stored separately for each user.

2017-01-18 17:42 UTC, brianghig requested changes
@allen12 the code looks good, but should we remove the fh* prefix on the modal?

2017-01-18 17:42 UTC, brianghig commented on src/client/app/justifications/justifications-modal.component.ts
> +	@ViewChild('fhJustificationsModal') private modal: ModalDirective;
Should we remove this prefix? Any issue with naming it 'justificationsModal' ?

2017-01-19 20:46 UTC, allen12 commented on src/client/app/justifications/justifications-modal.component.ts
> +	@ViewChild('fhJustificationsModal') private modal: ModalDirective;
That's a good point, I've since changed this to `justificationsModalChild` instead.

2017-01-19 20:48 UTC, allen12 commented
That's a good point, I've since changed this to `justificationsModalChild` instead.

2017-01-20 00:10 UTC, brianghig approved these changes

2017-01-20 18:43 UTC, closed without merging

2017-01-21 02:14 UTC, reblace commented
just fyi, we've moved this back into the project specific repo