Configure codeclimate checks
Asymmetrik/mean2-starter pull request #70
Opened 2017-01-30 15:29 UTC by bodnarbm

- Adds the `.codeclimate.yml` file to reuse eslint rules from the config/build/eslint.conf.json
- Ensure editors respect yaml required spacing in `.yml` files.

2017-01-30 15:42 UTC, brianghig requested changes
Looks like this breaks the publishing of coverage results to CodeClimate with the CODECLIMATE_REPO_TOKEN that's set as an environment variable in Travis-CI. Check out the last line of output at https://travis-ci.org/Asymmetrik/mean2-starter/builds/196620028

2017-01-30 16:17 UTC, bodnarbm commented
@brianghig That is because I am a fork and encrypted environment variables are not present for forks in travis. Code coverage will be uploaded upon merge.

2017-01-30 16:21 UTC, bodnarbm commented
Updated PR with moving eslint config to repo root, per request from @reblace

2017-01-30 16:30 UTC, brianghig approved these changes

2017-01-31 01:10 UTC, brianghig commented
@ymao1 @mheir are you guys okay with moving the `eslint.conf.json` file to the root at `.eslintrc`? @bodnarbm mentioned that it would break IDEs if you have those configured, though it should be a fairly quick fix.

2017-01-31 01:21 UTC, mheir commented
@brianghig @ymao1  I think intellij will detect the file as long as it is in the project somewhere, but I would need to test it.  I'd be ok with moving it, but we're starting to mix up where config files are a bit.  Right now we also have tsconfig.json, package.json, .editorconfig in the root directory while we then have some up in config/build (such as sasslint, tslint and webpack.conf.js).  There are also a bunch of others in just config as well as others I'm probably forgetting about right now.  Let's have a quick discussion when we're together and see if we can come up with a way to consolidate these all a bit better

2017-01-31 02:26 UTC, reblace commented
From what I saw, Intellij only picks up the eslint config automatically if it's at the root of the project and called ".eslintrc".

In the beginning, I had been trying to keep all the config files in a config directory to avoid having 50 files at the top level of the project. But, more and more tools require them to be named specifically and located at the root of the project (hence the tsconfig.json at the top level). I started moving the config files to the root of the project for the smaller projects (angular2 projects, node modules, etc).

2017-01-31 20:06 UTC, merged