New User Request Emails
Asymmetrik/mean2-starter pull request #77
Opened 2017-02-06 15:53 UTC by matthewgaulin

This branch is branched off of https://github.com/Asymmetrik/mean2-starter/pull/76

2017-02-07 14:19 UTC, ymao1 commented on src/server/app/admin/controllers/users/users.authentication.server.controller.js
> +		url: 'http://' + req.headers.host + '/#/admin/users'
Can use template string here.

2017-02-07 14:27 UTC, ymao1 commented
I requested an account with a username that was already taken and I got a validation error back that said username was already taken, but the new account request email was also sent out. Maybe switch the order so user save needs to be successful before the email is sent out?

2017-02-07 15:07 UTC, matthewgaulin commented on src/server/app/admin/controllers/users/users.authentication.server.controller.js
> +		url: 'http://' + req.headers.host + '/#/admin/users'
fixed

2017-02-07 15:09 UTC, matthewgaulin commented
@ymao1 I moved the email to run in parallel with the auditing

2017-02-07 15:21 UTC, ymao1 commented
Verified

2017-02-07 15:21 UTC, ymao1 approved these changes

2017-02-07 19:32 UTC, brianghig requested changes

2017-02-07 19:32 UTC, brianghig commented on src/server/app/admin/controllers/users/users.authentication.server.controller.js
> +	}, function(error, html) {
Arrow function?

2017-02-07 19:32 UTC, brianghig commented on src/server/app/admin/controllers/users/users.authentication.server.controller.js
> +		url: 'http://' + req.headers.host + '/#/admin/users'
Only `http`?

2017-02-07 20:16 UTC, reblace commented on src/server/app/admin/controllers/users/users.authentication.server.controller.js
> +		url: 'http://' + req.headers.host + '/#/admin/users'
Probably safe to assume we'll always have https enabled.

2017-02-07 22:30 UTC, matthewgaulin commented on src/server/app/admin/controllers/users/users.authentication.server.controller.js
> +		url: 'http://' + req.headers.host + '/#/admin/users'
So I just commited a change that adds the url to the config and pulls that instead of pulling from the header.  Let me know what you guys think.

2017-02-08 00:55 UTC, brianghig commented on src/server/config.js
> +let initDerivedConfig = (config) => {
Nice

2017-02-08 20:42 UTC, brianghig requested changes

2017-02-08 20:42 UTC, brianghig commented on src/server/app/admin/controllers/users/users.password.server.controller.js
> +					logger.error({err: error, req: req}, 'Failure sending email.');
Do we need a `done(error);` here to make sure that the promise is resolved/rejected, or is that unnecessary?

2017-02-08 21:13 UTC, matthewgaulin commented on src/server/app/admin/controllers/users/users.password.server.controller.js
> +					logger.error({err: error, req: req}, 'Failure sending email.');
Oops, I had a fix for this, but forgot to push it last night.  Let me know if its ok now.

2017-02-10 14:23 UTC, brianghig approved these changes

2017-02-10 14:24 UTC, merged